### ISSUE TITLE
Addition Request /playingart?sid=1

### ISSUE THREAD

**Issue by BlueFishey** [Wavestreaming/jquery-shoutcast#11]
Hi 

Great Code I love it !!! Coud you add in the Playing/Album Art to the code ?

Blue

**Comment by BlueFishey** [comment]
Is it ok if i add the lines to the easySetup.js or Jquery.shoutcast.js ?

I have created a 2nd version of jquery.shoutcast.easy.min.js as i run 2 steams, is it possible to to create a varible to enable 2 3 4 5 etc running on the same page ??

Blue

**Comment by jmulvany** [comment]
We aren't actively maintaining this as our efforts are now focused on https://radio.co - however, you're welcome to fork this branch and edit or modify it to suit your needs.
