### ISSUE TITLE
Script not working with my settings

### ISSUE THREAD

**Issue by DaradiciLevente** [Wavestreaming/jquery-shoutcast#14]
Hi ! I trying with this settings but not display any data from server

`
<!DOCTYPE html>
   <html>
   <head>
      <title>My Radio Station</title>
   </head>
   <body>
      
      <h1 data-shoutcast-value="servertitle"></h1>
      
      <p>Now Playing: <span data-shoutcast-value="songtitle"></span></p>
      <p>Listeners: <span data-shoutcast-value="currentlisteners"></span>/<span data-shoutcast-value="maxlisteners"></span></p>
      
      <h2>You just missed</h2>
      <ul id="played"></ul>
      
      
      <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
      <script src="jquery.shoutcast.easy.min.js?host=212.108.200.53:7210&port=7210"></script>
   </body>
   </html>`

How it's possible to solve this ?

**Comment by Jontyy** [comment]
Hi,

Change the last script tag to the following:

```html
<script src="jquery.shoutcast.easy.min.js?host=212.108.200.53&port=7210"></script>
```

The port was included in the host param :)

**Comment by DaradiciLevente** [comment]
Same results after this exchange: http://imgur.com/jWbHoT6
[img]http://i.imgur.com/jWbHoT6.png[/img]

It's possible to make this working for this stations ?

**Comment by DaradiciLevente** [comment]
I try with other stations, but same error.

```
`<title>My Radio Station</title>

  <h1 data-shoutcast-value="servertitle"></h1>
  
  <p>Now Playing: <span data-shoutcast-value="songtitle"></span></p>
  <p>Listeners: <span data-shoutcast-value="currentlisteners"></span>/<span data-shoutcast-value="maxlisteners"></span></p>
  
  <h2>You just missed</h2>
  <ul id="played"></ul>
  
  
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script src="jquery.shoutcast.easy.min.js?host=http://tachyon.shoutca.st&port=8098"></script>`
```

**Comment by echosmart792** [comment]
<title>My Radio Station</title>

  <h1 data-shoutcast-value="servertitle"></h1>
  
  <p>Now Playing: <span data-shoutcast-value="songtitle"></span></p>
  <p>Listeners: <span data-shoutcast-value="currentlisteners"></span>/<span data-shoutcast-value="maxlisteners"></span></p>
  
  <h2>You just missed</h2>
  <ul id="played"></ul>
  
  
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script src="jquery.shoutcast.easy.min.js?host=http://tachyon.shoutca.st&port=8098"></script>

**Comment by Jontyy** [comment]
Ahh sorry, just realised your steam is shoutcast V1, you will need to get some sort of server side solution for this, JSON functionality was only introduced to DNAS v2.

Something like this will do the trick https://github.com/Wavestreaming/SHOUTcast-PHP-Class

The second station uses shoutcast v2 so it will work: 
`<script src="jquery.shoutcast.easy.min.js?host=tachyon.shoutca.st&port=8098"></script>`

Example here: http://jsbin.com/rineyejelo/edit?html,css,js,output
